/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carrentalsystem;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Krishnamohan
 */
public class addCar extends javax.swing.JFrame {

    /**
     * Creates new form addCar
     */
    public addCar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regno = new javax.swing.JTextField();
        chasno = new javax.swing.JTextField();
        brand = new javax.swing.JTextField();
        color = new javax.swing.JTextField();
        rf = new javax.swing.JTextField();
        ff = new javax.swing.JTextField();
        date = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        cc = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Car");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(regno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 100, -1));

        chasno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chasnoActionPerformed(evt);
            }
        });
        getContentPane().add(chasno, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 100, -1));
        getContentPane().add(brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 100, -1));
        getContentPane().add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 100, -1));
        getContentPane().add(rf, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 100, -1));

        ff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ffActionPerformed(evt);
            }
        });
        getContentPane().add(ff, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 100, -1));
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        jLabel10.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Add Car");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        cc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Condition", "Brand New", "Healthy", "Usable" }));
        getContentPane().add(cc, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 100, -1));

        jLabel1.setText("Register No.");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel2.setText("Chassis No.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel3.setText("Brand");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel4.setText("Color");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jLabel5.setText("Rental Fee");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jLabel6.setText("Fine Fee");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jLabel7.setText("Date of Purchase");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jLabel8.setText("Car Condition");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        jButton1.setText("Add Car");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, -1, -1));

        jLabel9.setDisplayedMnemonic('A');
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrentalsystem/bg1.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chasnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chasnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chasnoActionPerformed

    private void ffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ffActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sregno=regno.getText();
        String schasno=chasno.getText();
        String sbrand=brand.getText();
        String scolor=color.getText();
        String srf=rf.getText();
        String sff=ff.getText();
        String scc=cc.getSelectedItem().toString();
        Date sdate=(Date) date.getDate();
        getTable gt=new getTable("Select regno from car where regno='"+sregno+"'");
        getTable gt1=new getTable("Select chassisno from car where chassisno='"+schasno+"'");
        if(sregno.equals("") || schasno.equals("")|| sbrand.equals("")|| scolor.equals("")|| srf.equals("")|| sff.equals("")|| scc.equals("Select a Condition")|| sdate==null){
            JOptionPane.showMessageDialog(this, "Make sure all the fields are filled");
        }
        else if (schasno.matches(".*\\D.*") || Double.parseDouble(schasno)!=(int)Double.parseDouble(schasno)){
            JOptionPane.showMessageDialog(this, "Chassis Number can only contain integers");
        }
        else if (scolor.matches(".*\\d.*")){
            JOptionPane.showMessageDialog(this, "Color can contain only alphabets");
        }
        else if (srf.matches(".*\\D.*") || sff.matches (".*\\D.*")){
            JOptionPane.showMessageDialog(this, "Rental Fee and Fine Fee can contain only numbers ");
        }
        else if (gt.getData()!=null){
            JOptionPane.showMessageDialog(this, "The register number already exists");
        }
        else if (gt1.getData()!=null){
            JOptionPane.showMessageDialog(this, "The chassis number already exists");
        }
        else{
            SimpleDateFormat sf=new SimpleDateFormat("yyyy-MM-dd");
            String ssdate=sf.format(sdate);
            String col="regno,chassisno,brand,dateOfPurchase,color,rentalfee,carcondition,finefee";
            String val="'"+sregno+"',"+schasno+",'"+sbrand+"','"+ssdate+"','"+scolor+"',"+srf+",'"+scc+"',"+sff;
            int res=JOptionPane.showConfirmDialog(this, "Are you sure that you want to complete this process?");
                    if (res==0){
                         saveToTable st=new saveToTable("car",val,col);
                         this.dispose();
                    }
            
        }
            
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brand;
    private javax.swing.JComboBox<String> cc;
    private javax.swing.JTextField chasno;
    private javax.swing.JTextField color;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTextField ff;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField regno;
    private javax.swing.JTextField rf;
    // End of variables declaration//GEN-END:variables
}
