/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carrentalsystem;


import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;




/**
 *
 * @author Krishnamohan
 */

public class addRental extends javax.swing.JFrame {

    /**
     * Creates new form addRental
     */
    
    protected static String custID="";
    protected static String carID="";
    
    public addRental() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        customerID = new javax.swing.JLabel();
        lcarID = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rentedday = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        payt = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Rental");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Add Rental");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jButton1.setText("Find Customer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        customerID.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        getContentPane().add(customerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 208, 34));

        lcarID.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        getContentPane().add(lcarID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 208, 32));

        jButton2.setText("Find Car");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 152, -1));

        jLabel1.setText("Date Rented");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel2.setText("No. of Days Rented");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        rentedday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renteddayActionPerformed(evt);
            }
        });
        getContentPane().add(rentedday, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 129, -1));

        jLabel3.setText("Payment Type");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        payt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Type", "Credit Card", "Cash" }));
        payt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paytActionPerformed(evt);
            }
        });
        getContentPane().add(payt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 129, -1));

        jButton3.setText("Add Rental");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jLabel4.setDisplayedMnemonic('A');
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrentalsystem/bg1.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SearchCustomer sc= new SearchCustomer();
        sc.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        searchCar scr=new searchCar();
        scr.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String pt=payt.getSelectedItem().toString();
        String rd=rentedday.getText();
        Date rented=(Date)jDateChooser1.getDate();
        int rentd;
        Calendar c=Calendar.getInstance();
        
        if (pt.equals("Select a Type") || custID.equals("") || carID.equals("")|| rd.equals("") || rented==null){
            JOptionPane.showMessageDialog(this,"Please make sure you have chosen a customer, a car and filled all other fields."," Empty Field",JOptionPane.WARNING_MESSAGE);
        }
        else if ((!rd.equals("") && (rd.matches(".*\\D.*") || Double.parseDouble(rd)!=(int)Double.parseDouble(rd) || Double.parseDouble(rd)==0))){
            JOptionPane.showMessageDialog(this,"Rented days can contain only integers and cannot be zero","Incompatible data type", JOptionPane.WARNING_MESSAGE);
        }
        else {
            
            SimpleDateFormat ft=new SimpleDateFormat("yyyy-MM-dd");
            String renteddate=ft.format(rented);
            c.setTime(rented);
            rentd=Integer.parseInt(rd);    
            c.add(Calendar.DATE,rentd);
            String dueDate=ft.format(c.getTime());
            String aquery="Select rentalfee from car where carid="+carID;
            getTable gt=new getTable(aquery);
            
            double rentalfee=Double.parseDouble(gt.getData());
            double total=rentalfee*rentd;
            String query=custID+","+carID+",'"+dueDate+"','"+renteddate+"','"+pt+"',"+total+","+Login.staffid;
            
            String col="customerid,carid,dueDate,rentedDate,paymentType,totalAmount,staffID";
            int res=JOptionPane.showConfirmDialog(this, "Are you sure that you want to complete this process?");
            if (res==0){
                
                
                saveToTable st=new saveToTable();
                String rentidp=st.getID("rental",query,col);
                System.out.println(rentidp);
                int rentidpi=Integer.parseInt(rentidp);
                HashMap param=new HashMap();
                param.put("@rid",rentidpi);
                invoiceRent mr=new invoiceRent("F:\\Desktop\\ST PROJECT\\CarRentalSystem\\report1.jasper",param);
                mr.setVisible(true);
                
                this.dispose();
            }
            
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void paytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paytActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paytActionPerformed

    private void renteddayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renteddayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_renteddayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addRental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addRental().setVisible(true);
            }
        });
    }
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected static javax.swing.JLabel customerID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    protected static javax.swing.JLabel lcarID;
    private javax.swing.JComboBox<String> payt;
    private javax.swing.JTextField rentedday;
    // End of variables declaration//GEN-END:variables
}
