/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carrentalsystem;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;

/**
 *
 * @author Krishnamohan
 */
public class handover extends javax.swing.JFrame {

    /**
     * Creates new form handover
     */
    public handover() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rentid = new javax.swing.JTextField();
        date = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hover = new javax.swing.JButton();
        condition = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jLabel10.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Add Staff");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Handover Car");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Eras Bold ITC", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Handover Car");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));
        getContentPane().add(rentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 130, -1));
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 130, -1));

        jLabel2.setText("Rental ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jLabel3.setText("Handed over Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel4.setText("Handed over Condition");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        hover.setText("Hand Over");
        hover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoverActionPerformed(evt);
            }
        });
        getContentPane().add(hover, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        condition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Condition", "Original", "Damaged" }));
        getContentPane().add(condition, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrentalsystem/bg1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoverActionPerformed
        // TODO add your handling code here:
        String rentalid=rentid.getText();
        String conditions=condition.getSelectedItem().toString();
        Date hdate=(Date) date.getDate();
        getTable gt4=new getTable("select rentalid from handover where rentalID="+rentalid);
        
        if ( rentalid.equals("") || conditions.equals("Select a Condition") || hdate==null){
           JOptionPane.showMessageDialog(this, "Please make sure all the fields have been filled!");
        }
        else if (rentalid.matches(".*\\D.*") || Double.parseDouble(rentalid)!=(int)Double.parseDouble(rentalid)){
            JOptionPane.showMessageDialog(this,"Rental ID can only contain integers!");
        }
        else if(gt4.getData()!=null){
            JOptionPane.showMessageDialog(this,"Rental ID already exists!");
        }
        else{
            try{
                String query="Select dueDate from rental where rentalID="+rentalid;
                getTable gt= new getTable(query);
                String duedate=gt.getData();
                SimpleDateFormat sf=new SimpleDateFormat("yyyy-MM-dd");
                String query2="Select carid from rental where rentalID="+rentalid;
                getTable gt1=new getTable(query2);
                String carid=gt1.getData();
                String query1="Select rentalfee from car where carid="+carid;
                getTable gt2=new getTable(query1);

                String handate=sf.format(hdate);

                double fined=Double.parseDouble(gt2.getData());
                double fine;
                try {
                    Date due=sf.parse(duedate);
                    long extradayst=hdate.getTime()-due.getTime();
                    double extradays=extradayst/(24 * 60 * 60 * 1000);
                    if(extradays<=0){
                        fine=0;
                    }
                    else{
                        System.out.println(extradays);
                        fine=fined*extradays;
                    }
                    String cols="rentalID,hDate,hcondition,fine";
                    String val=rentalid+",'"+handate+"','"+conditions+"',"+fine;
                    int res=JOptionPane.showConfirmDialog(this, "Are you sure that you want to complete this process?");
                    if (res==0){
                        saveToTable st=new saveToTable("handover",val,cols);
                        getTable gt3=new getTable("select hID from handover where rentalid="+rentalid);
                        String hid=gt3.getData();
                        String upq1="handoverID="+hid;
                        String upq2="rentalID="+rentalid;
                        updateTable ut=new updateTable("rental",upq1,upq2);
                        int rentidi=Integer.parseInt(rentalid);
                        HashMap param=new HashMap();
                        param.put("hid",rentidi);
                        invoiceRent mr=new invoiceRent("F:\\Desktop\\ST PROJECT\\CarRentalSystem\\report3.jasper",param);
                        mr.setVisible(true);
                        this.dispose();
                    }
                }
                catch (Exception e){

                }
            }
            catch (NullPointerException e){
                JOptionPane.showMessageDialog(this, "Rental ID not found!");
            }
        }
    }//GEN-LAST:event_hoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(handover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(handover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(handover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(handover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new handover().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> condition;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JButton hover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField rentid;
    // End of variables declaration//GEN-END:variables
}
