/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carrentalsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author Krishnamohan
 */
public class searchCar extends javax.swing.JFrame {

    /**
     * Creates new form searchRental
     */
    public searchCar() {
        initComponents();
        String c="select * from car where carid not in (select carid from rental) or (carid in (select carid from rental where handoverID IS NOT NULL) and carid not in (select carid from rental where handoverID IS NULL))";
        tableload cart=new tableload(c,jTable1,"just");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        brand = new javax.swing.JTextField();
        color = new javax.swing.JTextField();
        rentf = new javax.swing.JTextField();
        finef = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rentt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        finet = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Car");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 653, 395));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, -1, -1));
        getContentPane().add(brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 130, -1));
        getContentPane().add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 130, -1));
        getContentPane().add(rentf, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 59, -1));
        getContentPane().add(finef, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 57, -1));

        jLabel10.setFont(new java.awt.Font("Eras Bold ITC", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Search Car");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        jLabel1.setText("Brand");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel2.setText("Color");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel3.setText("Rental Fee");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));
        getContentPane().add(rentt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 59, -1));

        jLabel4.setText("From");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        jLabel5.setText("To");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        jLabel6.setText("Car Condition");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Condition", "Brand New", "Healthy", "Usable" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        jLabel7.setText("Fine ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));
        getContentPane().add(finet, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 61, -1));

        jLabel8.setText("From");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));

        jLabel9.setText("To");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, -1, -1));

        jButton2.setText("Select");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 540, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrentalsystem/bg2.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sbrand=brand.getText();
        String scolor=color.getText();
        String srentf=rentf.getText();
        String srentt=rentt.getText();
        String scondition=jComboBox1.getSelectedItem().toString();        
        String sfinef=finef.getText();
        String sfinet=finet.getText();
        
        
        if ((!srentf.equals("") && srentf.matches(".*\\D.*")) || (!srentt.equals("") && srentt.matches(".*\\D.*"))|| (!sfinef.equals("") && sfinef.matches(".*\\D.*")) || (!sfinet.equals("") && sfinet.matches(".*\\D.*"))){
            JOptionPane.showMessageDialog(this, "The rent and fine fileds may contain only numbers","Error",JOptionPane.WARNING_MESSAGE);
        }
        else if(scolor.matches(".*\\d.*")){
            JOptionPane.showMessageDialog(this, "Color may contain only alphabets");
        }
        else if (sbrand.equals("") && scolor.equals("") && srentf.equals("")&& srentt.equals("")&& sfinef.equals("")&&sfinet.equals("")&&scondition.equals("Select a Condition")){
            JOptionPane.showMessageDialog(this, "Make sure you have filled at least one field");
        }
        else{
            String qsbrand="brand='"+sbrand+"' and ";
            String qscolor="color='"+scolor+"' and ";
            String qsrent="rentalfee between "+srentf+" and "+srentt+" and ";
            String qsrentt="rentalfee<"+srentt+" and ";
            String qsrentf="rentalfee>"+srentf+" and ";
            String qscondition="carcondition='"+scondition+"' and ";        
            String qsfine="finefee between "+sfinef+" and "+sfinet+" and ";
            String qsfinef="finefee<"+sfinet+" and ";
            String qsfinet="finefee>"+sfinef+" and ";

            if ("Select a Condition".equals(scondition)){
                qscondition="";
            }
            if (sbrand.equals("")){
                qsbrand="";
            }
            if (scolor.equals("")){
                qscolor="";
            }
            if (srentf.equals("")){
                qsrent=qsrentt;
            }
            if (srentt.equals("")){
                qsrent=qsrentf;
            }
            if (srentf.equals("") &&srentt.equals("") ){
                qsrent="";
            }
            if (sfinet.equals("")){
                qsfine=qsfinef;
            }
            if (sfinef.equals("")){
                qsfine=qsfinet;
            }
            if (sfinef.equals("") && sfinet.equals("") ){
                qsfine="";
            }

            String newq="select * from car\n" +
            "where "+qsbrand+qscolor+qsrent+qscondition+qsfine+"(carid not in (select carid from rental) or carid in ((select carid from rental h\n" +
            "where handoverID IS NOT NULL) and carid not in (select carid from rental where handoverID IS NULL)))"; 

            tableload rents= new tableload(newq,jTable1, "just");
        }
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int r=jTable1.getSelectedRow();
        
        if (r>=0){
           String id=jTable1.getValueAt(r, 0).toString();
           String brandl= jTable1.getValueAt(r, 3).toString();
           
           addRental.carID=id;
           addRental.lcarID.setText(id+" "+brandl);
           this.dispose(); 
        }
        else{
            JOptionPane.showMessageDialog(this,"Please select a row", "No Row Selected", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField brand;
    private javax.swing.JTextField color;
    private javax.swing.JTextField finef;
    private javax.swing.JTextField finet;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField rentf;
    private javax.swing.JTextField rentt;
    // End of variables declaration//GEN-END:variables
}
