/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carrentalsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author Krishnamohan
 */
public class SearchCustomer extends javax.swing.JFrame {

    /**
     * Creates new form SearchCustomer
     */
   
    public SearchCustomer() {
        initComponents();
        String s="customer";
        tableload cus= new tableload(s,jTable1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        custName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        custId = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        cusNIC = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        cusPhone = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        select = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Customer");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 774, 347));
        getContentPane().add(custName, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 109, -1));

        jLabel6.setFont(new java.awt.Font("Eras Bold ITC", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Search Customer");
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, -1, -1));

        custId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custIdActionPerformed(evt);
            }
        });
        getContentPane().add(custId, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 90, -1));

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));
        getContentPane().add(cusNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 96, -1));

        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));
        getContentPane().add(cusPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, 99, -1));

        jButton4.setText("Search");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 160, -1, -1));

        select.setText("Select");
        select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectActionPerformed(evt);
            }
        });
        getContentPane().add(select, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 560, -1, -1));

        jLabel1.setText("Customer ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        jLabel2.setText("Customer NIC Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, -1));

        jLabel3.setText("Customer Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));

        jLabel4.setText("Customer Phone No.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, -1, -1));

        jLabel5.setDisplayedMnemonic('S');
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carrentalsystem/bg2.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (custName.getText()==null || "".equals(custName.getText())){
            JOptionPane.showMessageDialog(this,
            "Please enter a Customer Name",
            "Required Field Empty",
            JOptionPane.WARNING_MESSAGE);
        }
        else{
            String tableName="customer";
            String fieldName="FirstName";
            String searchName=custName.getText();
            tableload name= new tableload(tableName,fieldName,searchName,jTable1);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (custId.getText()==null || "".equals(custId.getText())){
            JOptionPane.showMessageDialog(this,
            "Please enter a Customer ID",
            "Required Field Empty",
            JOptionPane.WARNING_MESSAGE);
        }
        else if (custId.getText().matches(".*\\D.*") || Double.parseDouble(custId.getText())!=(int)Double.parseDouble(custId.getText())){
            JOptionPane.showMessageDialog(this, "Only integers are allowed for Customer ID!");
        }
        else{
            String tableName="customer";
            String fieldName="CustomerID";
            String searchName=custId.getText();
            tableload id= new tableload(tableName,fieldName,searchName,jTable1);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (cusNIC.getText()==null || "".equals(cusNIC.getText())){
            JOptionPane.showMessageDialog(this,
            "Please enter a Customer NIC  Number",
            "Required Field Empty",
            JOptionPane.WARNING_MESSAGE);
        }
        else if (!cusNIC.getText().matches("^[0-9]{9}[V|v]")){
            JOptionPane.showMessageDialog(this,"Please enter a valid NIC Number");
        }
        else{
            String tableName="customer";
            String fieldName="NIC";
            String searchName=cusNIC.getText();
            tableload nic= new tableload(tableName,fieldName,searchName,jTable1);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (cusPhone.getText()==null || "".equals(cusPhone.getText())){
            JOptionPane.showMessageDialog(this,
            "Please enter a Customer Phone Number",
            "Required Field Empty",
            JOptionPane.WARNING_MESSAGE);
        }
        else if(!cusPhone.getText().matches(".*\\d.*") || Double.parseDouble(cusPhone.getText())!=(int)Double.parseDouble(cusPhone.getText())){
            JOptionPane.showMessageDialog(this,"Phone number may only contain inetgers");
        }
        else{
            String tableName="customer";
            String fieldName="ContactNo";
            String searchName=cusPhone.getText();
            tableload phone= new tableload(tableName,fieldName,searchName,jTable1);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectActionPerformed
        // TODO add your handling code here:
        
        int r=jTable1.getSelectedRow();
       
        if (r>=0){
           String id=jTable1.getValueAt(r, 0).toString();
           String First= jTable1.getValueAt(r, 1).toString();
           String Last= jTable1.getValueAt(r, 2).toString();
           addRental.custID=id;
           addRental.customerID.setText(id+" "+First+" "+Last);
           this.dispose(); 
        }
        else{
            JOptionPane.showMessageDialog(this,"Please select a row", "No Row Selected", JOptionPane.WARNING_MESSAGE);
        }
        
        
        
        
     
    }//GEN-LAST:event_selectActionPerformed

    private void custIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchCustomer().setVisible(true);
            }
        });
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cusNIC;
    private javax.swing.JTextField cusPhone;
    private javax.swing.JTextField custId;
    private javax.swing.JTextField custName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton select;
    // End of variables declaration//GEN-END:variables
}
